### ISSUE TITLE
Error in input hook

### ISSUE THREAD

**Issue by glebqip** [INPStarfall/Starfall#260] opened 2014-09-05 15:21 UTC
I have 2 chips. 1st have a output, second a input. It's connected. When i change output, chip crashes with:

```
sv: Wire error (Entity [459][starfall_screen]):
addons/starfall/lua/starfall/instance.lua:84: assertion failed!
stack traceback:
    [C]: in function 'assert'
    addons/starfall/lua/starfall/instance.lua:84: in function 'prepare'
    addons/starfall/lua/starfall/instance.lua:215: in function '(for generator)'
    addons/starfall/lua/starfall/instance.lua:145: in function 'runScriptHook'
    addons/starfall/lua/entities/starfall_screen/shared.lua:15: in function 'runScriptHook'
    addons/starfall/lua/starfall/libs_sv/wire.lua:16: in function <addons/starfall/lua/starfall/libs_sv/wire.lua:15>
    [C]: in function 'xpcall'
    addons/wire/lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
    addons/wire/lua/wire/server/wirelib.lua:523: in function 'Wire_TriggerOutput'
    addons/starfall/lua/starfall/libs_sv/wire.lua:413: in function '__newindex'
    SF:starfall/SGC_Address_Book_v1.txt:124: in function 'func'
    ...
    addons/starfall/lua/starfall/instance.lua:69: in function 'runWithOps'
    addons/starfall/lua/starfall/instance.lua:217: in function '(for generator)'
    addons/starfall/lua/starfall/instance.lua:145: in function 'runScriptHook'
    addons/starfall/lua/entities/starfall_screen/shared.lua:15: in function 'runScriptHook'
    addons/starfall/lua/starfall/libs_sv/wire.lua:16: in function <addons/starfall/lua/starfall/libs_sv/wire.lua:15>
    [C]: in function 'xpcall'
    addons/wire/lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
    addons/wire/lua/wire/server/wirelib.lua:523: in function 'TriggerOutput'
    addons/wire/lua/entities/gmod_wire_keyboard/init.lua:204: in function 'KeyPressed'
    addons/wire/lua/entities/gmod_wire_keyboard/init.lua:296: in function <addons/wire/lua/entities/gmod_wire_keyboard/init.lua:270>
```

**Comment by awilliamson** [comment] 2014-09-05 15:23
Code would be nice to try and reproduce the bug.

**Comment by glebqip** [comment] 2014-09-05 15:30
``` lua
--@name Out
--@author glebqip(RUS)

wire.adjustOutputs({"Output"},{"string"})

wire.ports.Output = tostring(math.random(-100,100))
```

---

``` lua
--@name Inpur
--@author glebqip(RUS)

wire.adjustInputs({"Input"},{"string"})

hook.add("input","qwe",function(Name,Val) print(Name, Val) end)
```

---

Spawn 2 chips, connect it and update a Output chip. You must get a error.

**Comment by awilliamson** [comment] 2014-09-05 17:38
I ran both chips, wired them up, and "Input -95" popped up in chat. Appears to work, cannot reproduce, closing until such a time as somebody can prove this is broken.

**Comment by glebqip** [comment] 2014-09-05 18:29
But, i have this bug. Have you **update Output chip** after connecting?

**Comment by awilliamson** [comment] 2014-09-05 18:30
Ensure you are using the latest INPStarfall repo for this.

**Comment by glebqip** [comment] 2014-09-05 18:31
**awilliamson**, i use a official latest starfall (not TSCM)...

**Comment by Mijyuoon** [comment] 2014-09-05 18:38
The fix:

``` lua
function ENT:runScriptHook(hook, ...)
    if self.instance and not self.instance.error and self.instance.hooks[hook:lower()] then
        local instance = SF.instance  -- !! ADD THIS !!
        SF.instance = nil  -- !! ADD THIS !!
        local ok, rt = self.instance:runScriptHook(hook, ...)
        SF.instance = instance  -- !! ADD THIS !!
        if not ok then self:Error(rt) end
    end
end

function ENT:runScriptHookForResult(hook,...)
    if self.instance and not self.instance.error and self.instance.hooks[hook:lower()] then
        local instance = SF.instance  -- !! ADD THIS !!
        SF.instance = nil  -- !! ADD THIS !!
        local ok, rt = self.instance:runScriptHookForResult(hook, ...)
        SF.instance = instance  -- !! ADD THIS !!
        if not ok then self:Error(rt)
        else return rt end
    end
end
```

**Comment by Xandaros** [comment] 2014-09-05 18:41
This only happens because you are trying to link two starfalls. I just explained to Radon how to fix it. (Thank you @Mijyuoon, my solution is basically the same, but at a different location)

Instead of linking two starfalls, you can use remote hooks, you know... that's why they exist :P

**Comment by awilliamson** [comment] 2014-09-05 18:42
Seemed to misunderstand the initial bug reporting. Wasn't aware that this happens when updating the output chip after wiring. Looking into this now, I am indeed getting a silent error in console.

**Closed as completed** 2014-09-05 19:11 UTC
